name: env_conda
channels:
  - conda-forge
  - psi4
  - acellera
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - alabaster=0.7.12
  - babel=2.8.0
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.9.2
  - docutils=0.16
  - idna=2.9
  - imagesize=1.2.0
  - jinja2=2.11.2
  - ld_impl_linux-64
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20181209
  - libffi=3.3
  #- libgcc-ng=9.1.0
  #- libgfortran-ng=7.5.0
  - liblapack=3.8.0
  - libllvm10=10.0.1
  - libopenblas=0.3.10
  #- libstdcxx-ng=9.1.0
  - markupsafe=1.1.1
  - ncurses=6.2
  - openssl=1.1.1g
  - packaging=20.3
  - pip=20.0.2
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.8.3
  - python_abi=3.8
  - pytz=2020.1
  - readline=8.0
  - requests=2.23.0
  - setuptools=46.4.0
  - six=1.15.0
  - snowballstemmer=2.0.0
  - sphinx=3.0.3
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.31.1
  - tk=8.6.8
  - urllib3=1.25.8
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - attrs==19.3.0
    - backcall==0.1.0
    - biopython==1.77
    - bleach==3.1.5
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - freesasa==2.0.5.post2
    - idisplay==0.1.2
    - ipykernel==5.3.0
    - ipython==7.14.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.0
    - joblib==0.15.1
    - json5==0.9.5
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.3
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - jupyterlab==2.1.3
    - jupyterlab-server==1.1.5
    - kiwisolver==1.2.0
    - llvmlite==0.32.1
    - logomaker==0.8
    - matplotlib==3.2.1
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbformat==5.0.6
    - notebook==6.0.3
    - numba==0.49.1
    - numpy==1.18.4
    - pandas==1.0.3
    - pandocfilters==1.4.2
    - parso==0.7.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prody==1.10.11
    - prometheus-client==0.8.0
    - prompt-toolkit==3.0.5
    - ptyprocess==0.6.0
    - py3dmol==0.8.0
    - pyrsistent==0.16.0
    - python-dateutil==2.8.1
    - pyzmq==19.0.1
    - qtconsole==4.7.4
    - qtpy==1.9.0
    - scikit-learn==0.23.1
    - scipy==1.4.1
    - send2trash==1.5.0
    - sklearn==0.0
    - sphinx-rtd-theme==0.4.3
#    - tbb==2020.0.133
    - terminado==0.8.3
    - testpath==0.4.4
    - threadpoolctl==2.0.0
    - tornado==6.0.4
    - traitlets==4.3.3
    - wcwidth==0.1.9
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
